config/routes.rb
Rails.application.routes.draw do
  get 'watchlists/create'
  get 'watchlists/destroy'
  root to: "toppages#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "dashborad", to: "users#show"
  get "signup", to: "users#new"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "search", to: "stocks#index"
  resources :users, only: [:show,:new,:create,:edit,:update,:destroy]
  resources :stocks, only: [:show, :new, :create, :destroy]
  resources :comments, only: [:create,:destroy]
  resources :watchlists, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :stock
  validates :content, presence: true, length: { maximum: 500 }
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :comments
    has_many :commenters, through: :comments, source: :user
    def feed_comments
        Comment.where(user_id: self.commenters, stock_id: self.id)
    end

    has_many :watchlists
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :comments ,dependent: :destroy
  def post_comment(stock_instance,comment_params)
      self.comments.create(stock_id: stock_instance.id, content: comment_params)
  end

  has_many :watchlists ,dependent: :destroy
  has_many :watched_stocks, through: :watchlists,source: :stock
  
  def add_to_list(stock)
    self.watchlists.find_or_create_by(stock_id: stock.id)
  end
  def remove_from_list(stock)
    relationship = self.watchlists.find_by(stock_id: stock.id)
    relationship.destroy if relationship
  end
  
  def stock_exist?(stock)
    self.watched_stocks.include?(stock)
  end
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :require_user_logged_in
before_action :correct_user, only: [:destroy]

  def create
    stock_insatnce = Stock.find(params[:stock_id])
    current_user.post_comment(stock_insatnce,comment_params[:content])
    flash[:success] = 'The comment has been saved.'
    redirect_to stock_insatnce
  end
  
  # def update
  #   stock_insatnce = Stock.find(params[:id])
  #   current_user.post_comment(stock_insatnce)
  #   flash[:success] = 'コメントを保存しました'
  #   redirect_to stock_insatnce
  # end
  def destroy
    @comment.destroy
    flash[:success] = 'The comment has been deleted.'
    redirect_back(fallback_location: root_path)
  end
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
  def correct_user
  @comment = current_user.comments.find_by(id: params[:id])
    unless @comment
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success]="Successfully logined."
      redirect_to @user
    else
      flash.now[:danger]="Failed to login."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You logouted."
    redirect_to root_url
  end

  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
    
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
before_action :require_user_logged_in
require 'net/https'
require 'uri'
require 'json'
require 'time'

  def index
    @stocks = Stock.pluck(:id, :symbol, :name, :info)
    respond_to do |format|
      format.html
      format.json { render json: @stocks }
    end
  end

  def show
    @stock = Stock.find(params[:id])
    @comments = @stock.feed_comments
    symbol = @stock.symbol
    #finnhubアクセストークン
    token = ENV['FINNHUB']
    # token = ""
    t = Time.current
    end_time = t.to_i
    base_url = "https://finnhub.io/api/v1/stock/candle?symbol=#{symbol}&resolution=D&from=1546268400&to=#{end_time}&token=#{token}"
    # GETリクエストを送信する
    uri = URI.parse(base_url)
    response = Net::HTTP.get_response(uri)
    #Hash形式にparse    
    @result = JSON.parse(response.body)
      unless @result["s"] == "no_data"
        i=0
        count = @result["t"].length 
        @data = Array.new()
        while i < count 
          @data.push([@result["t"][i],@result["o"][i],@result["h"][i],@result["l"][i],@result["c"][i]])
          i = i + 1
        end 
        @data_json = @data.to_json.html_safe
      end
  end

  def create
  end

  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :require_user_logged_in, only: [:show,:edit]
  def show
    @user = User.find(params[:id])

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "Registration completed successfully."
      redirect_to @user
    else
      flash.now[:danger] = "Registration falled."
      render :new
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'Your infomation has successfully updated'
      redirect_to edit_user_path(@user)
    else
      flash.now[:danger] = 'Your infomation has failed to update'
      render :edit
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    flash[:success] ="Your account successfully deleted."
    redirect_to root_url
  end

private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
 before_action :require_user_logged_in

  def create
    stock = Stock.find(params[:stock_id])
    current_user.add_to_list(stock)
    flash[:success] = 'Added to your Watch List.'
    redirect_back(fallback_location: user_path(current_user))
  end

  def destroy
    stock = Stock.find(params[:stock_id])
    current_user.remove_from_list(stock)
    flash[:success] = 'Removed from your Watch List.'
    redirect_back(fallback_location: user_path(current_user))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
  </div>
<% end %>

app/views/layouts/_error_messages_email.html.erb
<% if model.errors[:email].any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
  </div>
<% end %>

app/views/layouts/_error_messages_name.html.erb
<% if model.errors[:name].any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
  </div>
<% end %>

app/views/layouts/_error_messages_pass.html.erb
<% if model.errors[:password].any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
  </div>
<% end %>
<% if model.errors[:password_confirmation].any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <%end%>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type,message|%>
  <% if message%>
    <div class="alert alert-<%= message_type%>"><%= message %><button type="button" class="close" data-dismiss="alert">&times;</button></div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="Footer">
    <div class="Footer__menu">
        <ul class="Footer__menuList">
            <li class="Footer__menuListItem">START</li>
            <li class="Footer__menuListItem">ABOUT</li>
        </ul>
    </div>
    <div class="Footer__copyright"><small>&copy; MARKET PURSER</small></div> 
</footer>

app/views/layouts/_navbar.html.erb
<header>
<% if logged_in? %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<% else %>
<nav class="navbar navbar-expand-sm navbar-light bg-light">
<% end %>
    <a class="navbar-brand" href="/">MARKET PURSER</a>
    <a class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fas fa-ellipsis-v"></i></a>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link">START</a></li>
        <li class="nav-item"><a class="nav-link">ABOUT</a></li>
        <% if logged_in? %>
        <li class="nav-item"><%= link_to "SEARCH", search_path, class:"nav-link" ,data: {"turbolinks" => false} %></li>
        <li class="nav-item"><%= link_to "DASHBOARD", current_user, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "SETTINGS",edit_user_path(current_user), class:"nav-link" ,data: {"turbolinks" => false}%></li>
        <li class="nav-item loginout-btn"><%= link_to "LOG OUT" ,logout_path, method: :delete ,class: "nav-link btn btn-dark text-light" %></li>
        <% else %>
        <li class="nav-item loginout-btn"><%= link_to "LOG IN", login_path, class: "nav-link btn btn-dark text-light" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketpurser</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.8.28/dayjs.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://kit.fontawesome.com/974c5dec76.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash_messages"%>
    <%= yield %>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/stocks/index.html.erb
<div class="container">
  <diV class ="text-center">
  <div class="border-bottom">
    <h1>SEARCH</h1>
  </div>
  <h2>Filterable Table</h2>
  <p>Type something in the Search field. You can find all US stocks, derivatives or cryptocurrencies.</p>  
  <br>
  <table id="myTable" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>No.</th>
        <th>Symbol</th>
        <th>Description</th>
        <th>Info</th>
      </tr>
    </thead>
    <tbody id="myTable">
    </tbody>
  </table>
  </div>
</div>

app/views/stocks/show.html.erb
<div class="container">
  <div class="text-center">
    <div class="border-bottom mb-2" >
      <h1>STOCK DETAIL</h1>
    </div>
    <h2><%= @stock.display_symbol %></h2>
    <p><%= @stock.name %></p>
  </div>
  
  <div class="text-right mb-3"><%= render 'watchlists/add_remove_button', stock: @stock %></div>

    <% unless @result["s"] == "no_data"  %>
      <div id="chart"></div>
      <input name="arr" type="hidden" value=<%= @data_json %> class='arr'>
    <% else %>
      <div class="text-center">
        <p>NO DATA</p>
      </div>
    <% end %>

  <div class="text-center">
    <h2>Comments</h2>
  </div>
    <div class="row">
      <div class="Form col-sm-12">
        <%= form_with(model:current_user.comments.build ,local: true) do |c| %>
        <%= hidden_field_tag :stock_id, @stock.id %>
        <div class="form-group mt-3">
          <%= c.text_area :content, class: 'form-control' %>
        </div>
        <%= c.submit 'SAVE', class: 'btn btn-primary btn-block' %>
        <% end %>
        <% @comments.each do |s| %>
          <% if s.user_id == current_user.id %>
            <div class="border-bottom mt-3 mb-3">
                <p class="mb-0">created at : <%= s.created_at %></p>
              <p><%= s.content%></p>
              <%= link_to "Delete", s , method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm mb-2' %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/toppages/index.html.erb
<div class="Cover">
  <div class="Cover__text text-center text-light">
    <h1 class="Cover__textHeading">Market Purser</h1>
    <p class="Cover__textCopy">Purse your asset slowly ,like wisely ...</p>
    <%= link_to "START FOR FREE",  signup_path, class: "Cover__textBtn btn btn-seconry bg-light" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
      
  <div class="text-center">
    <h1>SETTINGS</h1>
  </div>
  <div class="bg-seconry">
    <div class="row">
      <div class="col-sm-7 offset-sm-1">
          <%= form_with(model:@user,local: true) do |f| %>
          <%= render "layouts/error_messages_name", model: f.object %>
          <div class="form-group mb-3">
              <%= f.label :name, "Name" %>
              <%= f.text_field :name, class: "form-control" %>
          </div>
      </div>
      <div class="col-sm-3 d-flex align-items-end mb-3">
        <%= f.submit "SAVE" , class: "btn btn-primary form-control" %>
        <% end %>
      </div>
    </div>
    <div class="mt-3 border-bottom"></div>
  
    <div class="row">
      <div class="col-sm-7 offset-sm-1">
        <%= form_with(model:@user,local: true) do |f| %>
        <%= render "layouts/error_messages_email", model: f.object %>
        <div class="form-group mb-3">
          <%= f.label :email, "Email" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-3 d-flex align-items-end mb-3">
        <%= f.submit "SAVE" , class: "btn btn-primary form-control" %>
        <% end %>
      </div>
    </div>
    <div class="mt-3 border-bottom"></div>
      
    <div class="row">
      <div class="col-sm-7 offset-sm-1">
        <%= form_with(model:@user,local: true) do |f| %>
        <%= render "layouts/error_messages_pass", model: f.object %>
        <div class="form-group mb-3">
          <%= f.label :password, "Password" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group mb-3">
          <%= f.label :password_confirmation, "Password Confirmation" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-3 d-flex align-items-end mb-3">
        <%= f.submit "SAVE" , class: "btn btn-primary form-control" %>
        <% end %>
      </div>
    </div>
    <div class="mt-3 border-bottom"></div>
      <div class="text-center mt-3">
       <%= link_to "DELETE ACCOUNT", @user , method: :delete, data:{confirm: "Do you really want to delete your account?" },class: "btn btn-danger" %>
     </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="text-center">
    <h1>SIGN UP</h1>
  </div>
  <div class="row ">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model:@user,local: true) do |f| %>
      <%= render "layouts/error_messages", model: f.object%>
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>  
      
      <div class="form-group">
        <%= f.label :email, "Email" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>  
      
      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "Password Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
        <%= f.submit "SIGN UP" , class: "btn btn-primary btn-block" %>
        <% end %>
        <p>Already have an account? <%= link_to "Log in", login_path %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="text-center">
    <h1>DASHBOARD</h1>
  <h2>WATCH LIST</h2>
  </div>
  <div class="row">
  <div class="col-lg-8 offset-lg-2">
     <table class="table table-striped">
      <thead>
        <tr>
          <th>Manage</th>
          <th>Symbol</th>
          <th>Description</th>
          <th>Info</th>
        </tr>
      </thead>
        <tbody>
         <% @user.watched_stocks.each do |s| %>
          <tr>
            <td><%= render 'watchlists/add_remove_button', stock: s %></td>
            <td><%= link_to s.display_symbol,s ,data: {"turbolinks" => false} %></td>
            <td><%= link_to s.name, s,data: {"turbolinks" => false} %></td>
            <td><%= s.info %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/watchlists/_add_remove_button.html.erb
<% if current_user.stock_exist?(stock) %>
  
  <%= form_with(model: current_user.watchlists.find_by(stock_id: stock.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :stock_id, stock.id %>
    <%= f.submit 'Remove', class: 'btn btn-danger' %>
  <% end %>
  
<% else %>
  
  <%= form_with(model: current_user.watchlists.build, local: true) do |f| %>
    <%= hidden_field_tag :stock_id, stock.id %>
    <%= f.submit 'Add', class: 'btn btn-success' %>
  <% end %>
  
<% end %>